services:
  - type: web
    name: corte-certo
    env: python
    buildCommand: pip install -r requirements.txt && python init_database.py
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false